version: '3'
services:
  api:
    build: ./server/.
    container_name: agc-api
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
  
  redis_db:
    image: redis:3.2.8
    ports:
      - '6379:6379'
