version: '3'
services:
  api:
    build: ./server/.
    container_name: agc-api
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
    depends_on:
      - redis_db
  
  redis_db:
    image: redis:3.2.8
    ports:
      - '6379:6379'
